[icons]
name = "awesome"

[[block]]
block = "sound"
step_width = 3
on_click = "pavucontrol"

[[block]]
block = "net"
device = "wlp3s0"
speed_down = false 
speed_up = false
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% ({time})"

[[block]]
block = "time"
format = "%A, %B %-e  %R"
timezone = "US/Pacific"
interval = 60

